version: '3'
services:

  market-status:
    restart: always
    build: .
    image: market-status
    env_file:
      - .env
    ports:
      - 3000:3000

  nginx-market-status:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
